<a href="https://colab.research.google.com/github/Shraddha6211/Machine-Learning-Extra-Class/blob/main/ANN_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
from google.colab import files
files.upload()

Saving car_purchasing.csv to car_purchasing.csv

{'car_purchasing.csv': b'customer name,JobTitle,customer e-mail,country,gender,age,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,credit card debt,net worth,car purchase amount\r\nMartina Avila,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,cubilia.Curae.Phasellus@quisaccumsanconvallis.edu,Bulgaria,0,42,167411.18,0,400184.25,,567595.43,567595.43,11609.38091,238961.2505,35321.45877\r\nHarlan Barnes,CAPTAIN III (POLICE DEPARTMENT),eu.dolor@diam.co.uk,Belize,0,41,155966.02,245131.88,137811.38,,538909.28,538909.28,9572.957136,530973.9078,45115.52566\r\nNaomi Rodriquez,CAPTAIN III (POLICE DEPARTMENT),vulputate.mauris.sagittis@ametconsectetueradipiscing.co.uk,Algeria,1,43,212739.13,106088.18,16452.6,,335279.91,335279.91,11160.35506,638467.1773,42925.70921\r\nJade Cunningham,WIRE ROPE CABLE MAINTENANCE MECHANIC,malesuada@dignissim.com,Cook Islands,1,58,77916,56120.71,198306.9,,332343.61,332343.61,14426.16485,548599.0524,67422.36313\r\nCedric Leach,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",felis.ullamcorper.viverra@egetmollislectus.net,Brazil,1,57,134401.6,9737,182234.59,,326373.19,326373.19,5358.712177,560304.0671,55915.46248\r\nCarla Hester,ASSISTANT DEPUTY CHIEF II,mi@Aliquamerat.edu,Liberia,1,57,118602,8601,189082.74,,316285.74,316285.74,14179.47244,428485.3604,56611.99784\r\nGriffin Rivera,"BATTALION CHIEF, (FIRE DEPARTMENT)",vehicula@at.co.uk,Syria,1,47,92492.01,89062.9,134426.14,,315981.05,315981.05,5958.460188,326373.1812,28925.70549\r\nOrli Casey,DEPUTY DIRECTOR OF INVESTMENTS,nunc.est.mollis@Suspendissetristiqueneque.co.uk,Czech Republic,1,50,256576.96,0,51322.5,,307899.46,307899.46,10985.69656,629312.4041,47434.98265\r\nMarny Obrien,"BATTALION CHIEF, (FIRE DEPARTMENT)",Phasellus@sedsemegestas.org,Armenia,0,47,176932.64,86362.68,40132.23,,303427.55,303427.55,3440.823799,630059.0274,48013.6141\r\nRhonda Chavez,"CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)",nec@nuncest.com,Somalia,1,43,285262,0,17115.73,,302377.73,302377.73,12884.07868,476643.3544,38189.50601\r\nJerome Rowe,"ASSISTANT CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)",ipsum.cursus@dui.org,Sint Maarten,1,50,194999.39,71344.88,33149.9,,299494.17,299494.17,8270.707359,612738.6171,59045.51309\r\nAkeem Gibson,CAPTAIN III (POLICE DEPARTMENT),turpis.egestas.Fusce@purus.edu,Greenland,1,53,99722,87082.62,110804.3,,297608.92,297608.92,10014.96929,293862.5123,42288.81046\r\nQuin Smith,EXECUTIVE CONTRACT EMPLOYEE,nulla@ipsum.edu,Nicaragua,0,44,294580.02,0,0,,294580.02,294580.02,10218.32092,430907.1673,28700.0334\r\nTatum Moon,DEPARTMENT HEAD V,Cras.sed.leo@Seddiamlorem.ca,"Palestine, State of",0,48,271329.03,0,21342.59,,292671.62,292671.62,9466.995128,420322.0702,49258.87571\r\nSharon Sharpe,"BATTALION CHIEF, (FIRE DEPARTMENT)",eget.metus@aaliquetvel.co.uk,United Arab Emirates,0,55,174872.64,74050.3,37424.11,,286347.05,286347.05,10597.63814,146344.8965,49510.03356\r\nThomas Williams,"COMMANDER III, (POLICE DEPARTMENT)",aliquet.molestie@ut.org,Gabon,1,53,198778.01,73478.2,13957.65,,286213.86,286213.86,11326.03434,481433.4324,53017.26723\r\nBlaine Bender,DEPARTMENT HEAD V,ultrices.posuere.cubilia@pedenonummyut.net,Tokelau,0,45,268604.57,0,16115.86,,284720.43,284720.43,11495.54999,370356.2223,41814.72067\r\nStephen Lindsey,"CAPTAIN, EMERGENCYCY MEDICAL SERVICES",erat.eget.ipsum@tinciduntpede.org,Portugal,1,48,140546.87,119397.26,18625.08,,278569.21,278569.21,12514.52029,549443.5886,43901.71244\r\nSloane Mann,"BATTALION CHIEF, (FIRE DEPARTMENT)",at.augue@augue.net,Chad,1,52,168692.63,69626.12,38115.47,,276434.22,276434.22,7377.820914,431098.9998,44633.99241\r\nAthena Wolf,ASSISTANT MEDICAL EXAMINER,volutpat.Nulla.facilisis@primis.ca,Iraq,0,59,257510.59,880.16,16159.5,,274550.25,274550.25,13272.94647,566022.1306,54827.52403\r\nBlythe Romero,ASSISTANT MEDICAL EXAMINER,Sed.eu@risusNuncac.co.uk,Sudan,1,52,257510.48,0,16679.79,,274190.27,274190.27,11878.03779,480588.2345,51130.95379\r\nZelenia Byers,ASSISTANT MEDICAL EXAMINER,auctor.non@sapien.co.uk,Angola,0,48,257510.44,377.21,15883.56,,273771.21,273771.21,10905.36628,307226.0977,43402.31525\r\nNola Wiggins,"CAPTAIN, FIRE SUPPRESSION",Aliquam@augue.edu,Nigeria,1,46,140546.88,93200.58,39955.25,,273702.71,273702.71,7698.552234,497526.4566,47240.86004\r\nMicah Wheeler,"BATTALION CHIEF, (FIRE DEPARTMENT)",arcu.eu@tincidunt.org,Madagascar,1,47,168692.63,77896.14,24083.86,,270672.63,270672.63,11960.85377,688466.0503,46635.49432\r\nCaryn Hendrix,"CAPTAIN, FIRE SUPPRESSION",condimentum.Donec@duiCum.com,Macedonia,0,40,140546.86,97868.77,31909.28,,270324.91,270324.91,8125.598993,499086.3442,45078.40193\r\nHedda Miranda,CHIEF OF POLICE,scelerisque@magnased.com,Oman,0,53,256470.41,0,11522.18,,267992.59,267992.59,17805.57607,429440.3297,44387.58412\r\nUlric Lynn,"CAPTAIN, FIRE SUPPRESSION",sociis@vulputateveliteu.com,Colombia,0,28,92080.8,40008,133695.76,,265784.56,265784.56,13102.15805,315775.3207,37161.55393\r\nAlma Pope,"BATTALION CHIEF, (FIRE DEPARTMENT)",Nunc.mauris.Morbi@turpis.org,Namibia,0,56,168692.59,80706.88,16063.99,,265463.46,265463.46,14270.00731,341691.9337,49091.97185\r\nGemma Hendrix,DEPUTY CHIEF III (POLICE DEPARTMENT),lobortis@non.co.uk,Denmark,1,46,261717.6,0,2357,,264074.6,264074.6,17452.92179,188032.0778,58350.31809\r\nCastor Wood,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",velit.Pellentesque@Nulla.net,Dominican Republic,1,40,246225.6,0,15140.54,,261366.14,261366.14,12522.94052,583230.976,43994.35972\r\nHerman Stevenson,EXECUTIVE CONTRACT EMPLOYEE,sociosqu.ad.litora@erat.com,Costa Rica,1,33,234325.02,0,25972.64,,260297.66,260297.66,9371.511071,319837.6593,17584.56963\r\nAdrienne Bolton,DEPUTY CHIEF III (POLICE DEPARTMENT),dictum@magnaPraesent.ca,Botswana,1,40,254027.63,0,5899.48,,259927.11,259927.11,13417.02027,486069.073,44650.36073\r\nDahlia Cleveland,DEPARTMENT HEAD V,tincidunt.tempus@idsapien.co.uk,Saint Pierre and Miquelon,1,51,248895.7,0,10789.18,,259684.88,259684.88,8092.475103,655934.4666,66363.89316\r\nKeane Browning,"INSPECTOR III, (POLICE DEPARTMENT)",Curabitur@acipsumPhasellus.co.uk,France,0,51,104861.39,50227.61,103499.39,,258588.39,258588.39,11417.30952,487435.964,53489.46214\r\nQuon Hull,"BATTALION CHIEF, (FIRE DEPARTMENT)",nascetur.ridiculus.mus@dignissim.co.uk,Senegal,0,46,177781.25,59924.97,20658,,258364.22,258364.22,7988.753685,215673.5384,39810.34817\r\nCoby Charles,ELECTRONIC MAINTENANCE TECHNICIAN,nec@dolornonummyac.com,Cambodia,0,51,101953.2,139102.95,16483.94,,257540.09,257540.09,12252.73058,612242.7755,51612.14311\r\nAmery Cortez,"ADMINISTRATOR, SFGH MEDICAL CENTER",semper.et.lacinia@Morbiquisurna.ca,Suriname,1,50,245124.44,0,12000,,257124.44,257124.44,7405.534271,430624.8142,38978.67458\r\nUriel Bradshaw,"INSPECTOR III, (POLICE DEPARTMENT)",ultrices@Integersemelit.com,Turkey,1,22,110661.2,31162.04,111446.2,,253269.44,253269.44,10917.14094,326742.7352,10092.22509\r\nFredericka Sanders,LIEUTENANT III (POLICE DEPARTMENT),Curabitur@Infaucibus.ca,Ethiopia,0,51,132202.26,52648.92,67083.83,,251935.01,251935.01,8838.759509,213040.9606,35928.52404\r\nChristopher Stevens,"BATTALION CHIEF, (FIRE DEPARTMENT)",blandit.enim@lacusvariuset.org,French Guiana,1,48,147158.85,64985.85,39540.46,,251685.16,251685.16,4499.921096,379749.9152,54823.19221\r\nRachel Ashley,"BATTALION CHIEF, (FIRE DEPARTMENT)",tincidunt.tempus.risus@posuerecubiliaCurae.co.uk,Turkey,0,42,168692.66,60847.56,21055.17,,250595.39,250595.39,9183.327621,513340.0097,45805.67186\r\nLael Wright,"BATTALION CHIEF, (FIRE DEPARTMENT)",a@consequatpurusMaecenas.com,Bhutan,1,46,168692.63,59760.9,21954.96,,250408.49,250408.49,12491.01273,410655.9947,41567.47033\r\nRyder Shaffer,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",Phasellus.dapibus.quam@inhendrerit.ca,Georgia,0,38,218930.76,4078,27330.59,,250339.35,250339.35,13338.32852,348833.8403,28031.20985\r\nEric Noel,FIREFIGHTER,lacinia.at.iaculis@Fuscefermentumfermentum.edu,Mozambique,1,39,123013.02,111729.65,15575.26,,250317.93,250317.93,10816.8855,299734.1278,27815.73813\r\nTamara Guy,NURSING SUPERVISOR PSYCHIATRIC,nec.eleifend@orci.org,Nauru,1,61,196081.86,0,54040.18,,250122.04,250122.04,14245.53319,497950.2933,68678.4352\r\nQuincy Bell,MAYOR,in@Duisgravida.co.uk,Timor-Leste,0,55,249375.02,0,0,,249375.02,249375.02,10155.34095,853913.8532,68925.09447\r\nLee Taylor,"BATTALION CHIEF, (FIRE DEPARTMENT)",Vivamus.nisi.Mauris@miAliquam.co.uk,Djibouti,1,42,168692.64,66199.23,14401.43,,249293.3,249293.3,11675.28496,320228.6451,34215.7615\r\nKenneth Pope,DEPARTMENT HEAD V,vitae.sodales.at@molestiearcuSed.org,Argentina,0,51,248895.77,0,0,,248895.77,248895.77,2230.096344,158979.7102,37843.46619\r\nReese Vance,DEPUTY CHIEF III (POLICE DEPARTMENT),egestas@malesuadavelvenenatis.com,Taiwan,1,41,233867.6,0,14851.04,,248718.64,248718.64,7094.896557,390312.1715,37883.24231\r\nQuon Carroll,"LIEUTENANT, FIRE DEPARTMENT",sodales@pharetra.com,\xc5land Islands,0,40,137729.92,89856.01,20848.46,,248434.39,248434.39,7915.758178,527420.7269,48734.35708\r\nMagee Davidson,"BATTALION CHIEF, (FIRE DEPARTMENT)",Quisque@tempor.net,Turks and Caicos Islands,1,41,168692.59,58084.86,20477.16,,247254.61,247254.61,11023.00268,451846.1995,27187.23914\r\nLeilani Gross,DEPARTMENT HEAD V,dignissim@mollisDuissit.org,Samoa,0,56,246305.62,0,0,,246305.62,246305.62,12378.54089,779925.7892,63738.39065\r\nMorgan William,"CAPTAIN, FIRE SUPPRESSION",sociis.natoque.penatibus@uterat.ca,Vanuatu,0,46,140546.87,77937.25,26203.69,,244687.81,244687.81,7813.602657,455609.1429,48266.75516\r\nFrancesca Cervantes,"CAPTAIN, FIRE SUPPRESSION",leo@sitametdapibus.edu,Mongolia,1,37,140546.88,73207.61,28988.36,,242742.85,242742.85,11216.88676,583523.0762,46381.13111\r\nRafael Peterson,"CAPTAIN, EMERGENCYCY MEDICAL SERVICES",lectus.a.sollicitudin@tortorat.net,Sri Lanka,1,52,140546.89,82428.76,18310.77,,241286.42,241286.42,1851.979839,353757.5057,31978.9799\r\nRoanna Knox,DEPUTY CHIEF III (POLICE DEPARTMENT),dolor.nonummy@metusurnaconvallis.net,Guinea-Bissau,0,57,226206.8,0,15004.37,,241211.17,241211.17,6998.46562,438067.7506,48100.29052\r\nMarny Vargas,DEPARTMENT HEAD V,nonummy.Fusce.fermentum@ligula.org,Egypt,1,34,240731.93,0,114.37,,240846.3,240846.3,7772.444847,468238.7915,47380.91224\r\nCharlotte Waller,ASSISTANT DEPUTY CHIEF II,odio@Nuncac.org,Slovenia,1,43,217410.8,0,22608.3,,240019.1,240019.1,11331.20447,636407.1148,41425.00116\r\nDorian Hernandez,INCIDENT SUPPORT SPECIALIST,conubia.nostra.per@diam.co.uk,Benin,1,50,115381.02,105028.94,19016.4,,239426.36,239426.36,7592.019748,409419.5797,38147.81018\r\nArmando Hensley,ANESTHETIST,Class.aptent@torquentper.com,Cape Verde,1,42,214745.44,9161.31,14972.45,,238879.2,238879.2,9976.434857,286062.5162,32737.80177\r\nRowan Kidd,"LIEUTENANT, FIRE DEPARTMENT",sapien.Aenean.massa@adipiscing.ca,Paraguay,1,42,123105,99584.94,16113.62,,238803.56,238803.56,7829.565502,615765.9289,37348.13737\r\nGwendolyn Rice,CAPTAIN III (POLICE DEPARTMENT),Duis@metusIn.com,Laos,0,42,102571.24,7437,128543.64,,238551.88,238551.88,4225.328117,476088.3996,47483.85316\r\nGareth Morris,"CAPTAIN, EMERGENCYCY MEDICAL SERVICES",est.Nunc.laoreet@nullavulputatedui.edu,Iceland,0,55,140546.86,80411.9,17542.29,,238501.05,238501.05,9842.842611,242495.9886,49730.53339\r\nSawyer Carney,"BATTALION CHIEF, (FIRE DEPARTMENT)",erat.Sed@Phasellus.ca,Iceland,0,53,168692.62,54342.28,15444.38,,238479.28,238479.28,15189.08845,246321.8916,40093.61981\r\nRaya Shields,LIEUTENANT III (POLICE DEPARTMENT),tincidunt.aliquam@orciluctuset.com,Viet Nam,0,53,148970.43,66977.63,21889.67,,237837.73,237837.73,9046.182396,456634.2073,42297.5062\r\nOlga Serrano,CAPTAIN III (POLICE DEPARTMENT),risus@urnasuscipitnonummy.edu,Marshall Islands,0,43,185369.69,37873.61,14465.53,,237708.83,237708.83,6841.540577,662176.4851,52954.93121\r\nYuli Craig,"ASSISTANT CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)",lobortis.quis.pede@Seddiam.com,Germany,0,55,177914.76,36644.57,22785.08,,237344.41,237344.41,11785.87919,301026.2206,48104.11184\r\nLev Kramer,"CAPTAIN, FIRE SUPPRESSION",eu.odio@tristique.org,Kyrgyzstan,1,43,139167.39,66596.28,31070.15,,236833.82,236833.82,8634.376791,573054.3808,43680.91327\r\nNissim Acosta,DEPUTY CHIEF III (POLICE DEPARTMENT),enim@at.net,Mauritius,1,57,122974,0,113226.92,,236200.92,236200.92,10886.91711,662382.6623,52707.96816\r\nMiranda Berry,INCIDENT SUPPORT SPECIALIST,lorem@necmauris.ca,Gambia,1,52,115455.44,104632.95,14776.81,,234865.2,234865.2,13685.88702,356553.3996,49392.8897\r\nOwen Jacobson,DISTRICT ATTORNEY,ac.orci@Etiamimperdietdictum.edu,"Palestine, State of",1,45,220983.12,0,13864.99,,234848.11,234848.11,11350.49408,230728.3008,30841.00154\r\nMarvin Becker,"BATTALION CHIEF, (FIRE DEPARTMENT)",congue.elit@vestibulumneceuismod.ca,Reunion,0,56,92782.61,5477.62,135684.25,,233944.48,233944.48,5627.803654,411831.0371,49373.37555\r\nDavis Scott,"ELECTRICAL TRANSIT MECHANIC, ASSISTANT SUPERVISOR",neque@variusultricesmauris.edu,Jordan,0,41,95770.8,118949.93,18743.9,,233464.63,233464.63,10676.21884,481335.3582,41903.65171\r\nMatthew Colon,PORT DIRECTOR,facilisis@Nullainterdum.edu,Slovakia,1,48,233357.28,0,0,,233357.28,233357.28,4630.544424,473845.8546,45058.8969\r\nQuinlan Harris,"INSPECTOR III, (POLICE DEPARTMENT)",libero.nec@adipiscing.org,Kiribati,1,56,130457.88,51864.26,50380.44,,232702.58,232702.58,13000.41369,355157.6417,52991.52667\r\nHedley Greene,"INSPECTOR III, (POLICE DEPARTMENT)",eleifend@felis.org,United States Minor Outlying Islands,0,47,85578.61,42878.01,104030.1,,232486.72,232486.72,15791.61176,506986.9824,50958.08115\r\nOrson Kirby,"BATTALION CHIEF, (FIRE DEPARTMENT)",cursus@nectellus.co.uk,Puerto Rico,1,53,174872.64,16876.74,40258.39,,232007.77,232007.77,16732.30638,344916.1768,41357.17897\r\nAdria Mathis,"LIEUTENANT, BUREAU OF FIRE PREVENTION AND PUBLIC S",Aliquam.rutrum.lorem@Donec.net,Guinea,1,57,73754.05,18679.06,139279.69,,231712.8,231712.8,8740.723093,309113.0627,44434.71917\r\nPeter Stout,"CAPTAIN, FIRE SUPPRESSION",dictum.mi.ac@semperrutrumFusce.com,Guam,0,39,140546.88,62283.7,28821.55,,231652.13,231652.13,10059.55406,278799.6958,38502.42392\r\nCleo Moore,"BATTALION CHIEF, (FIRE DEPARTMENT)",pede.et@Sedeu.com,China,0,45,168692.62,35096.74,27802.89,,231592.25,231592.25,861.8166529,540805.494,41221.24918\r\nCally Montoya,SENIOR PHYSICIAN SPECIALIST,sit@pedeCum.ca,Sierra Leone,1,33,172529.08,0,58776.96,,231306.04,231306.04,6147.918843,441527.0144,38399.46139\r\nIla Farrell,"LIEUTENANT, FIRE DEPARTMENT",lacus@velit.edu,Sint Maarten,1,44,122272.69,90593.53,18238.75,,231104.97,231104.97,9522.576495,523251.2663,41456.68097\r\nAbel Stanton,"BATTALION CHIEF, (FIRE DEPARTMENT)",eu.lacus.Quisque@congue.edu,Ecuador,1,40,168692.62,41158.72,21055.17,,230906.51,230906.51,9724.031647,407401.3776,30394.82494\r\nReed Roman,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,laoreet.libero@laoreetlectus.com,Anguilla,0,40,230827.12,0,0,,230827.12,230827.12,5449.471997,409293.2658,42384.05128\r\nSeptember Puckett,"CAPTAIN, EMERGENCYCY MEDICAL SERVICES",tincidunt@consequatpurusMaecenas.net,Kazakhstan,1,37,217410.8,0,13216.41,,230627.21,230627.21,9565.830875,386128.1333,39002.0771\r\nTeegan Barr,FIRE FIGHTER PARAMEDIC,non.lorem.vitae@eratVivamus.org,Jersey,1,40,122404.98,92767.41,15371.07,,230543.46,230543.46,9719.192898,245664.3652,19553.2739\r\nAlexander York,"BATTALION CHIEF, (FIRE DEPARTMENT)",eu.odio.Phasellus@ipsumporta.edu,Ecuador,1,44,150464.82,49813.69,30180.49,,230459,230459,11024.02643,496856.4912,45167.32542\r\nJared Green,MANAGER VII,laoreet@sagittis.edu,Macao,0,43,96814.36,0,133563.47,,230377.83,230377.83,11041.17891,448601.9484,36019.9556\r\nEagan Woodward,TRANSIT SUPERVISOR,varius.et@Maecenas.edu,Indonesia,1,58,88062,135159.38,7018.6,,230239.98,230239.98,4204.920492,388498.5102,50937.93844\r\nFerdinand Weber,"INSPECTOR, BUREAU OF FIRE PREVENTION AND PUBLIC SA",metus.Vivamus@vitaeposuere.org,Suriname,1,32,138878.82,31843.34,59427.12,,230149.28,230149.28,14261.80773,579181.6552,12895.71468\r\nKitra Kerr,"BATTALION CHIEF, (FIRE DEPARTMENT)",scelerisque@Vivamusnon.co.uk,Palau,1,50,188842.37,21453.59,18764.67,,229060.63,229060.63,8244.470226,173079.1798,38955.21919\r\nDesirae Stone,CAPTAIN III (POLICE DEPARTMENT),Morbi.sit@Aliquamfringilla.ca,Ghana,1,59,102722.4,7437,118456.21,,228615.61,228615.61,9871.403591,536665.0464,51221.04249\r\nLen Phillips,"CAPTAIN, FIRE SUPPRESSION",libero.lacus@Suspendisseseddolor.net,Cameroon,1,42,149362.84,51847.45,27303.11,,228513.4,228513.4,13865.09055,259049.2824,25971.95673\r\nYen Santana,CAPTAIN III (POLICE DEPARTMENT),ornare.facilisis@ornarelibero.ca,Myanmar,0,50,215914.03,0,12293.83,,228207.86,228207.86,10562.90377,635512.3606,60670.33672\r\nMartina Fuentes,"BATTALION CHIEF, (FIRE DEPARTMENT)",elit@nequeIn.com,Senegal,1,53,168692.62,33191.6,25434.68,,227318.9,227318.9,11794.73914,398746.8458,54075.12064\r\nAriana Nash,MANAGER VIII,vel.turpis.Aliquam@consequatpurus.edu,Central African Republic,1,47,215180.76,0,12000,,227180.76,227180.76,11030.2654,391848.6041,40004.87142\r\nGlenna Graham,ANESTHETIST,sodales@maurisSuspendisse.com,Bolivia,0,46,208925.6,5539.3,12615.6,,227080.5,227080.5,13872.5667,479586.9387,61593.52058\r\nHolmes Lane,"BATTALION CHIEF, (FIRE DEPARTMENT)",ac.orci@accumsaninterdum.co.uk,Laos,1,43,168692.67,35402.71,22261.95,,226357.33,226357.33,8870.714301,165866.2,39503.38829\r\nEmerald Hamilton,FIRE FIGHTER PARAMEDIC,sit.amet.orci@facilisis.edu,Egypt,0,49,122404.98,86719.38,15315.61,,224439.97,224439.97,5831.118245,515084.1891,52474.71839\r\nGage Marquez,DEPUTY DIRECTOR II - MUNICIPAL TRANSPORTATION AG,malesuada.vel@dictum.co.uk,Guam,0,43,224035.85,0,0,,224035.85,224035.85,16767.2636,759479.4596,42187.6828\r\nTravis Burks,"BATTALION CHIEF, (FIRE DEPARTMENT)",dictum@liberolacusvarius.ca,Namibia,1,53,168692.65,33656.87,21502.83,,223852.35,223852.35,5189.083564,706977.053,57441.44414\r\nOtto Oneill,"LIEUTENANT, FIRE DEPARTMENT",arcu.Morbi.sit@elementum.ca,Mozambique,1,36,123105,84547.16,16054.24,,223706.4,223706.4,11811.25253,242292.92,22681.71667\r\nBrian Mathews,FIREFIGHTER,vulputate.mauris.sagittis@orciluctus.com,Bhutan,1,30,105934.69,98534.35,18890.96,,223360,223360,7357.787011,404457.3099,33640.73697\r\nRalph Rich,TRANSIT SUPERVISOR,et@tellus.edu,Tuvalu,0,37,88400.7,126778.88,7228.67,,222408.25,222408.25,14562.64194,537744.1324,31540.77868\r\nYasir Tyler,FIREFIGHTER,pharetra.sed.hendrerit@adipiscinglobortisrisus.edu,Qatar,0,48,105934.64,97395.59,18760.77,,222091,222091,10614.85449,891439.8761,60461.24268\r\nDominic Mcintosh,FIREFIGHTER,Cras.vehicula@nibhPhasellusnulla.net,Venezuela,0,44,110474.93,83670.04,27043.61,,221188.58,221188.58,6280.929547,296972.4085,45738.3343\r\nTanner Ward,"BATTALION CHIEF, (FIRE DEPARTMENT)",diam@orciUt.ca,Togo,0,42,149362.86,35003.5,36682.96,,221049.32,221049.32,12416.84845,450402.2932,34803.82395\r\nWing Gray,NURSING SUPERVISOR,urna.nec@tempusscelerisquelorem.org,Nepal,1,50,188708,0,32080.36,,220788.36,220788.36,7335.524826,386057.421,34642.6024\r\nLionel Mcclure,NURSING SUPERVISOR,odio.auctor.vitae@placeratorcilacus.edu,Saudi Arabia,1,30,188708,0,32080.36,,220788.36,220788.36,10366.50326,323453.2022,27586.71854\r\nWing Parks,FIREFIGHTER,sagittis@magnased.ca,San Marino,1,42,105934.67,96154.33,18655.85,,220744.85,220744.85,9010.648633,778537.2095,54973.02495\r\nOleg Gordon,ANESTHETIST,Nunc.sollicitudin.commodo@blanditat.co.uk,Saint Lucia,1,46,206057.69,3431.01,10921.33,,220410.03,220410.03,9656.806156,386287.0208,49142.51174\r\nJamal Stephenson,POLICE OFFICER III,lorem.lorem@in.edu,Vanuatu,1,55,63811.18,57966.33,98578.97,,220356.48,220356.48,12887.54899,416540.299,58840.53964\r\nKadeem Larsen,DEPUTY DIRECTOR II - MUNICIPAL TRANSPORTATION AG,ornare.lectus.ante@lectusNullam.net,United Arab Emirates,0,44,220115.22,0,237,,220352.22,220352.22,1696.989764,562605.0655,57306.32866\r\nTodd Maldonado,NURSING SUPERVISOR,dui.semper.et@aultricies.net,Solomon Islands,0,58,188708,0,31572.3,,220280.3,220280.3,11211.72016,565932.1861,51941.6756\r\nVictor Yang,TRANSIT SUPERVISOR,arcu.Vivamus.sit@egestasSed.com,Andorra,1,42,88400.7,119951.72,11893.84,,220246.26,220246.26,7903.103591,238529.

In [7]:
import pandas as pd

df= pd.read_csv('car_purchasing.csv', encoding='latin1')
df.head(3)

,customer name,JobTitle,customer e-mail,country,gender,age,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,credit card debt,net worth,car purchase amount
0,Martina Avila,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,cubilia.Curae.Phasellus@quisaccumsanconvallis.edu,Bulgaria,0,42,167411.18,0.00,400184.25,NaN,567595.43,567595.43,11609.380910,238961.2505,35321.45877
1,Harlan Barnes,CAPTAIN III (POLICE DEPARTMENT),eu.dolor@diam.co.uk,Belize,0,41,155966.02,245131.88,137811.38,NaN,538909.28,538909.28,9572.957136,530973.9078,45115.52566
2,Naomi Rodriquez,CAPTAIN III (POLICE DEPARTMENT),vulputate.mauris.sagittis@ametconsectetueradip...,Algeria,1,43,212739.13,106088.18,16452.60,NaN,335279.91,335279.91,11160.355060,638467.1773,42925.70921

In [8]:
df= df.drop([
    'customer name',
    'customer e-mail',
    'country',
    'Benefits',
    'JobTitle'

], axis =1)
df.sample(3)

,gender,age,BasePay,OvertimePay,OtherPay,TotalPay,TotalPayBenefits,credit card debt,net worth,car purchase amount
69,1,52,115455.44,104632.95,14776.81,234865.20,234865.20,13685.887020,356553.3996,49392.88970
230,1,51,202426.74,0.00,0.00,202426.74,202426.74,5011.615145,563498.6636,52654.40455
232,1,46,139580.96,33418.92,29333.37,202333.25,202333.25,16127.566190,494985.5363,46054.60253

In [9]:
X = df.drop('car purchase amount', axis =1)
y = df['car purchase amount']
X.head(3)

,gender,age,BasePay,OvertimePay,OtherPay,TotalPay,TotalPayBenefits,credit card debt,net worth
0,0,42,167411.18,0.00,400184.25,567595.43,567595.43,11609.380910,238961.2505
1,0,41,155966.02,245131.88,137811.38,538909.28,538909.28,9572.957136,530973.9078
2,1,43,212739.13,106088.18,16452.60,335279.91,335279.91,11160.355060,638467.1773

In [12]:
# Create 3 classes using quantiles
y_class =pd.qcut(
    y,
    q=3,
    labels=[0,1,2]
)

# Convert category to int
y_class = y_class.astype(int)

In [13]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.utils import to_categorical
from sklearn.metrics import classification_report, confusion_matrix

In [14]:
y_cat = to_categorical(y_class, num_classes=3)
y_cat

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       ...,
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.]])

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y_cat, test_size=0.2, random_state=42)

In [16]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [17]:
model = keras.Sequential([
    layers.Dense(128, activation='relu', input_shape=(X_train.shape[1],)),
    layers.Dense(64, activation='relu'),
    layers.Dense(3, activation='softmax')       # 3 categorical outputs
])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [18]:
model.compile(
    optimizer = 'adam',
    loss = 'categorical_crossentropy',
    metrics = ['accuracy']
)

In [19]:
history = model.fit(
    X_train,
    y_train,
    epochs = 10,
    batch_size = 32,
    validation_split = 0.2,
    verbose =1
)

Epoch 1/10
10/10 ━━━━━━━━━━━━━━━━━━━━ 2s 50ms/step - accuracy: 0.3594 - loss: 1.1057 - val_accuracy: 0.3875 - val_loss: 1.0603
Epoch 2/10
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.5219 - loss: 0.9970 - val_accuracy: 0.5125 - val_loss: 1.0172
Epoch 3/10
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.6031 - loss: 0.9221 - val_accuracy: 0.5750 - val_loss: 0.9627
Epoch 4/10
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6531 - loss: 0.8524 - val_accuracy: 0.5750 - val_loss: 0.9123
Epoch 5/10
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6812 - loss: 0.7952 - val_accuracy: 0.5875 - val_loss: 0.8780
Epoch 6/10
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.6812 - loss: 0.7552 - val_accuracy: 0.5375 - val_loss: 0.8641
Epoch 7/10
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.6844 - loss: 0.7241 - val_accuracy: 0.5750 - val_loss: 0.8530
Epoch 8/10
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.6844 - loss: 0.7055 - val_accuracy: 0.5750 - val_loss: 0.8538
Epoch 9/10
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6781 - loss: 0.6920 - val_accuracy: 0.5750 - val_loss: 0.8640
Epoch 10/10
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6906 - loss: 0.6783 - val_accuracy: 0.5625 - val_loss: 0.8794

In [21]:
y_pred = np.argmax(model.predict(X_test), axis=-1)
y_true = np.argmax(y_test, axis=-1)

print(confusion_matrix(y_true, y_pred))
print(classification_report(y_true, y_pred))

4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step
[[23  5  0]
 [ 7 15 13]
 [ 2  6 29]]
              precision    recall  f1-score   support

           0       0.72      0.82      0.77        28
           1       0.58      0.43      0.49        35
           2       0.69      0.78      0.73        37

    accuracy                           0.67       100
   macro avg       0.66      0.68      0.66       100
weighted avg       0.66      0.67      0.66       100